version: '3'
services:
  frontend:
    image: yenaura/devtool-frontend-final:1.0.0
    build: ./front-end
    restart: always
    ports:
      - 3001:80
  backend:
    image: yenaura/devtool-backend-final:1.0.0
    build: ./back-end
    restart: always
    ports:
      - 4000:4000